name: forest_calc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipython
  - ipykernel
  - earthengine-api
  - matplotlib
  - flatdict
  - pandas
  - folium
  - contextily
  - geemap
  - geopandas
  - flask
  - requests
  - shiny
  - pip:
      - contextvars==2.4
      - htmltools==0.2.1
      - immutables==0.19
      - mdit-py-plugins==0.4.0
      - shiny==0.3.3
      - shinywidgets==0.2.1
